---

- name: Create the directory for raspberrypi configuration
  file:
    path:  '{{ item }}'
    owner: root
    group: root
    mode:  0755
    state: directory
  with_items:
    - '{{ raspberrypi__custom_scripts_directory }}'

- name: Create config.txt configuration file
  template:
    src:   config.txt.j2
    dest:  '{{ raspberrypi__config_file }}'
    owner: root
    group: root
    mode:  0755

- name: Read current cmdline options string
  slurp:
    src: '{{ raspberrypi__cmdline_file }}'
  register: _raspberrypi__cmdline_raw
  check_mode: no

- name: Format cmdline
  set_fact:
    _raspberrypi__cmdline: '{{ _raspberrypi__cmdline_raw.content|b64decode }}'

- name: Add cmdline options
  set_fact:
    _raspberrypi__cmdline: "{{ [_raspberrypi__cmdline|trim, item.option]|join(' ') }}"
  with_items: '{{ raspberrypi__cmdline_options }}'
  when: item.state|d('present') == 'present' and item.option not in _raspberrypi__cmdline

- name: Remove cmdline options
  set_fact:
    _raspberrypi__cmdline: "{{ _raspberrypi__cmdline|replace(item.option, '') }}"
  with_items: '{{ raspberrypi__cmdline_options }}'
  when: item.state|d('present') == 'absent' and item.option in _raspberrypi__cmdline

- name: Save cmdline options into file
  copy:
    dest:    '{{ raspberrypi__cmdline_file }}'
    content: "{{ _raspberrypi__cmdline|trim~'\n' }}"
    owner:   root
    group:   root
    mode:    0755

- name: Install custom raspberrypi scripts files
  copy:
    src:   '{{ item }}'
    dest:  '{{ raspberrypi__custom_scripts_directory }}/{{ item }}'
    owner: root
    group: root
    mode:  0755
  with_items:
    - raspberrypi_check_firmware_update.sh
