---

- name: Create custom fact directory
  file:
    path:  "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode:  0755
    state: directory

- name: Insert custom fact file
  copy:
    src:  files/raspberrypi.py
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/raspberrypi.fact"
    mode: 0755
