---
# tasks file for raspberrypi

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- include_tasks: facts.yml
  when: raspberrypi__facts|bool

- import_tasks: configure.yml
  tags: ['raspberrypi', 'raspberrypi-configure']

- import_tasks: service.yml
  tags: ['raspberrypi', 'raspberrypi-service']

- include_tasks: 'monitoring-{{ raspberrypi__monitoring }}.yml'
  when: raspberrypi__monitoring is defined
  tags: ['raspberrypi', 'raspberrypi-monitoring']
