---

- name: Configure zabbix userparameters available by vcgencmd
  include_role:
    name: zabbix-agent
    tasks_from: userparameter
  vars:
    zabbix_agent__userparameters:
      name: vcgencmd
      comment: Theses items get the hardware information of the Raspberry PI using the vcgencmd command
      userparameters:
        - key: raspberry.cpu.temperature
          command: cat /sys/class/thermal/thermal_zone0/temp
          comment: Get CPU core temperature. exemple "45622" for 45.6 C
        - key: raspberry.voltage[*]
          command: >
            /bin/bash -c 'expr "$(/usr/bin/vcgencmd measure_volts $1)" : "volt=\([0-9\.]\+\)V"'
          sudo: True
          sudo_user: root
          comment: voltages
        - key: raspberry.frequency[*]
          command: >
            /bin/bash -c 'expr "$(/usr/bin/vcgencmd measure_clock $1)" : "frequency([0-9]\+)=\([0-9]\+\)"'
          sudo: True
          sudo_user: root
          comment: frequencies
        - key: raspberry.firmware_version
          command: >
            /bin/bash -c 'expr "$(/usr/bin/vcgencmd version)" : ".*version \([^ ]*\)"'
          sudo: True
          sudo_user: root
          comment: Firmware version
      state: present

- name: Configure zabbix userparameters for raspberrypi
  include_role:
    name: zabbix-agent
    tasks_from: userparameter
  vars:
    zabbix_agent__userparameter:
      name: raspberrypi
      comment: Miscellaneous for raspberry pi
      userparameters:
        - key: raspberry.firmware_update
          command: '{{ raspberrypi__custom_scripts_directory }}/raspberrypi_check_firmware_update.sh 2>/dev/null | grep --count UPDATE_AVAILABLE'
          sudo: True
          sudo_user: root
          comment: Firmware version updates
      state: present
