---

- name: Ensure hciuart is started and enabled on boot
  service:
    name:    '{{ raspberrypi__hciuart_service }}'
    enabled: '{{ raspberrypi__hciuart_service_enabled|bool }}'
    state:   "{{ raspberrypi__hciuart_service_enabled|bool|ternary('started', 'stopped') }}"
  when: (ansible_local.raspberrypi.hardware_revision_informations.model_version_major)|d(0)|version_compare('3', '>=')
